name: Murat Abur
description: Streams of unconciousness
meta_description: "Thoughts, experiences and theories"

markdown: kramdown
highlighter: pygments
logo: true
paginate: 20
baseurl: /
domain_name: 'http://'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://muratabur@github.io'
author:         'murat'
author_description:	'The author is present'