# Site settings
title: Streams of Unconciousness
email: 
description: > 
  The theories and experiences of Murat Abur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://muratabur.github.io" # the base hostname & protocol for your site
twitter_username: not-on-twitter
github_username:  muratabur

# Build settings
markdown: kramdown
