name: rubatarum
description: streams of unconciousness...
meta_description: "Thoughts, experiences and theories"

markdown: kramdown
highlighter: rouge
logo: true
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page:num"
baseurl: /
domain_name: 'http://'
google_analytics: 'UA-68523005-1'
